version: '3.8'

services:
  web:
    build: .
    ports:
      # Map container port 8080 to host port 8080
      - "8080:8080"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_SERVER: db 
      POSTGRES_DB: shortener_db
      REDIS_HOST: redis 
      BASE_URL: http://localhost:8080
    
    # Ensures the application waits for the DB before running uvicorn
    command: /app/healthcheck.sh db uvicorn app.main:app --host 0.0.0.0 --port 8080
    
    depends_on:
      - db
      - redis
    stop_signal: SIGINT

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortener_db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  tests:
    build: .
    command: pytest -v
    depends_on:
      - web
      - db
      - redis
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_SERVER: db
      POSTGRES_DB: shortener_db
      REDIS_HOST: redis
      BASE_URL: http://localhost:8080


volumes:
  postgres_data:
